### PR TITLE
Fix: add alpha premultiplication steps before and after resize

### PR DESCRIPTION
**Pull request by KaarlisCaune**
First of all, thank you for the great work!

I noticed an issue with resizing images that have an alpha channel. Since vips was introduced, white shapes on transparent background started having dark edges after resize. Project I'm working on contains many such images, and after the jekyll picture tag update most of them are displayed with unwanted dark borders.

Example (original source on left, resized image on right):

edges

You can test it with this source image - resize it via the tag and view it on a light background:

source

The issue stems from premultiplication of the alpha channel. [vips documentation](https://github.com/libvips/libvips/wiki/HOWTO----Image-shrinking) advises to [premultiply the alpha channel](https://github.com/libvips/libvips/wiki/HOWTO----Image-shrinking#premultiply) on images before resize, then [resize](https://github.com/libvips/libvips/wiki/HOWTO----Image-shrinking#premultiply), then [unpremultiply alpha again](https://github.com/libvips/libvips/wiki/HOWTO----Image-shrinking#premultiply) - this PR does exactly that.

Disclaimer: I haven't checked the performance hit of this change, nor do I have the ruby chops to only run this when an alpha channel is actually present or similarly optimise it.

### CODE REVIEW

**Comment by rbuchberger** [comment]
Thanks for the bug report and the PR! Unfortunately it looks like it breaks the tests, so it'll need a little more investigation.

I'll have to do some learning about this issue and see what I can come up with.

**Comment by KaarlisCaune** [comment]
We tried this change in production via a monkey-patch and it caused bugs when resizing images that don't have an alpha channel. 
For context:
* libvips assumes the last band of an image to be the alpha channel when running `premultiply`
* If the image is RGBA, it's the last one - alpha, and everything's alright
* If the image is RGB, the blue channel will be used instead, causing the resulting image to be basically yellow - green 😬 

I updated the PR to only run the premultiplication / unpremultiplication steps when applicable.
Not sure if the resizing bug is related to this bug as well.

**Comment by rbuchberger** [comment]
Thanks! Looks like that change fixed the test, likely because the test image doesn't have an alpha channel. That said, I'd like to add a test of an image which does have an alpha channel. Feel free to add it yourself, or I'll add one when I get the chance. If you do add a test image to the repo, please keep it small (I believe the existing images are 100px squares).

**Comment by KaarlisCaune** [comment]
I'm surprised it passes now 😅  This version did fix the yellow images, but I experienced an issue where the images with alpha channel would not get resized at all (files with proper widths in filenames would be generated, but all in the same original width).

I managed to fix it in my patch version by "chaining" the operations on image like this:

```ruby
def resize(image)
  if image.has_alpha?
    image = image.premultiply
    image = image.resize(scale_value)
    image.unpremultiply
  else
    image.resize(scale_value)
  end
end
```
I'm not well versed in ruby, but I suppose the issue was me assuming the image object will be mutated on each step, resulting in sequential actions. This version doesn't assume that and seems to finally work as expected on my project.
Can I ask for a sanity check of this code? 

I can try adding a test case with alpha transparency 👍

**Comment by rbuchberger** [comment]
Heh, you've run into one of the reasons why I don't write much ruby anymore. Does the premultiply command modify the existing instance? Who knows! We have to run it and find out. `require 'pry'; binding.pry` will get you a debug console on that particular line where you can run ruby commands.

**Comment by KaarlisCaune** [comment]
Looks like it needs the assignment after each modification, otherwise it will only return the last one (thus skip the resize step).

I managed to add a test case for images with alpha transparency (which fails if I remove the object assignment).

**Review by rbuchberger — APPROVED** [review]
Looks good to me! Outstanding work, thank you.

**Comment by rbuchberger** [comment]
I'll get a release out soon, but until then you can pull from the master branch to get them immediately.

**Pull request merged**
